### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Elinor78** [Elinor78/cpp-adv-eng#1]
- [x] Preliminary Requirements Document
  - [x] Preliminary Project Description
  - [x] Rapid Prototype
  - [x] Use Case Diagrams
- [ ] Software Project Plan
   - [ ] Cost and Duration Estimation
   - [x] Extended Project Description
   - [ ] Project resources
   - [ ] Schedule
   - [ ] Staff Organization
- [ ] Requirements Analysis
   - [x] ER Diagrams
   - [ ] Business Rules
   - [x] Hardware Requirements
   - [x] Preliminary Database Design
   - [x] Preliminary Class Diagrams
   - [x] Revised GUI
   - [x] Scope and Purpose
- [ ] Design Spec Document
   - [x] Complete Class Diagram
   - [x] Final GUI Design
   - [x] Pseudo Code for all functions
   - [ ] Sequencing Diagrams
- [ ] Final Report User Manual
   - [ ] Final Report
   - [x] User Manual
